etianguis/api/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from api.views import *

urlpatterns = [
    #   Product endpoints
    url(r'^products/$', ProductsList.as_view()),
    url(r'^products/(?P<pk>[0-9]+)/$', ProductsDetail.as_view()),

    #   User endpoints
    url(r'^users/$', UsersList.as_view()),
    url(r'^users/(?P<pk>[0-9]+)/$', UsersDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

etianguis/applications/urls.py
from django.conf.urls import url
from applications.views import *

urlpatterns = [
    #   User related urls
    url(r'^login/', UserLogin.as_view(), name='login'),
    url(r'^signup/', UserCreate.as_view(), name='signup'),
    url(r'^logout/', UserLogout.as_view(), name='logout'),

    #   Products related urls
    url(r'^product_list/', ProductList.as_view(), name='products'),
    url(r'^product_create/', ProductCreate.as_view(), name='product_create'),
    url(r'^product_detail/(?P<pk>[0-9]+)', ProductDetail.as_view(),
        name='product_detail'),
    url(r'^product_purchase/(?P<pk>[0-9]+)', ProductPurchase.as_view(),
        name='product_purchase'),
    url(r'^product_delete/(?P<pk>[0-9]+)', ProductDelete.as_view(),
        name='product_delete'),

    #   User actions related urls
    url(r'^purchases/', UserPurchases.as_view(), name="purchases"),
    url(r'^products/', UserProducts.as_view(), name="my_products"),

    #   Index view
    url(r'^$', IndexView.as_view(), name='index'),
]

etianguis/etianguis/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^applications/', include('applications.urls',
                                   namespace='applications')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/v1/', include('api.urls', namespace="api")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    #   API Login endpoint
    url(r'^auth/', include('rest_framework.urls',
                           namespace='rest_framework')),
]

etianguis/applications/models.py
from django.db import models
from django.contrib.auth.models import User


class Producto(models.Model):
    id_usuario = models.ForeignKey(User, default=1)
    nombre = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=500)
    imagen = models.ImageField(upload_to='products', blank=True)
    precio = models.PositiveIntegerField(default=1)
    fecha_publicacion = models.DateTimeField(auto_now_add=True, blank=True)
    cantidad = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.nombre


class Transaccion(models.Model):
    id_producto = models.ForeignKey('Producto')
    id_usuario = models.ForeignKey(User, default=1)
    fecha = models.DateField(auto_now_add=True, blank=True)
    cantidad = models.PositiveIntegerField(default=1)

etianguis/applications/views.py
from django.shortcuts import redirect
from django.contrib.auth import login, logout
from django.views.generic import TemplateView, ListView, DetailView
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.views.generic.edit import CreateView, DeleteView, FormView
from applications.models import Producto, Transaccion
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.urlresolvers import reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.messages.views import SuccessMessageMixin
# from django.contrib.auth.models import User


class IndexView(TemplateView):
    template_name = "applications/index.html"


class ProductCreate(SuccessMessageMixin, CreateView):

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ProductCreate, self).dispatch(request, *args, **kwargs)

    model = Producto
    fields = ['nombre', 'descripcion', 'imagen', 'precio']
    success_url = reverse_lazy('applications:products')
    success_message = "Your product was created successfully"

    def form_valid(self, form):
        user = self.request.user
        form.instance.id_usuario = user
        return super(ProductCreate, self).form_valid(form)


class ProductList(ListView):
    model = Producto
    template_name = "applications/products.html"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        user = self.request.user
        self.queryset = Producto.objects.exclude(
            id_usuario=user).exclude(cantidad=0)
        return super(ProductList, self).dispatch(request, *args, **kwargs)


class ProductDetail(SuccessMessageMixin, DetailView):
    model = Producto

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ProductDetail, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ProductDetail, self).get_context_data(**kwargs)
        return context


class ProductDelete(SuccessMessageMixin, DeleteView):
    model = Producto
    success_url = reverse_lazy('applications:products')
    success_message = "Product deleted successfully."
    template_name = "applications/confirm_delete.html"


class ProductPurchase(SuccessMessageMixin, CreateView):
    model = Transaccion
    fields = ['cantidad']
    success_url = reverse_lazy('applications:products')
    success_message = "Product purchased successfully."
    template_name = "applications/product_purchase.html"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        producto = Producto.objects.get(pk=self.kwargs['pk'])
        producto.cantidad -= 1
        return super(ProductPurchase, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = self.request.user
        actual_primary_key = self.kwargs['pk']
        producto = Producto.objects.get(pk=actual_primary_key)
        form.instance.id_usuario = user
        form.instance.id_producto = producto
        producto.cantidad -= 1
        producto.save()
        self.Transaccion = form.save()
        return super(ProductPurchase, self).form_valid(form)


class UserCreate(SuccessMessageMixin, CreateView):
    form_class = UserCreationForm
    template_name = "applications/user_form.html"
    success_url = reverse_lazy('applications:index')
    success_message = "User was created successfully"


class UserLogin(SuccessMessageMixin, FormView):
    form_class = AuthenticationForm
    template_name = "applications/login.html"
    success_url = reverse_lazy('applications:products')
    success_message = "Welcome back %(username)s!"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect(self.get_success_url())
        else:
            return super(UserLogin, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        login(self.request, form.get_user())
        return super(UserLogin, self).form_valid(form)


class UserLogout(RedirectView):
    pattern_name = 'applications:index'

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(UserLogout, self).get(request, *args, **kwargs)


class UserProducts(ListView):
    model = Producto
    template_name = "applications/user_products.html"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        user = self.request.user
        self.queryset = Producto.objects.filter(id_usuario=user)
        return super(UserProducts, self).dispatch(request, *args, **kwargs)


class UserPurchases(ListView):
    model = Transaccion
    template_name = "applications/user_purchases.html"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        user = self.request.user
        self.queryset = Transaccion.objects.filter(id_usuario=user)
        return super(UserPurchases, self).dispatch(request, *args, **kwargs)

etianguis/applications/templates/applications/confirm_delete.html
<!DOCTYPE html>
<html>
<head>
    <title>Delete Product</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm" />
    </form>
</body>
</html>

etianguis/applications/templates/applications/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link href="{%static 'styles.css'%}" rel="stylesheet">
</head>
<body>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<div class="container">
    <div id="header" class="row">
        <p>Welcome to eTianguis</p>
    </div>
</div>

<div class="container">
    <div id="buttons" class="row">
        <a href="login">Login</a>
        <a href="signup">Sign up</a>
    </div>
</div>

</body>
</html>

etianguis/applications/templates/applications/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<form action="." method="post">
	{% csrf_token %}
    {{ form.as_p }}
    <input type="submit">Login</input>
</form>
</body>
</html>

etianguis/applications/templates/applications/product_purchase.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" placeholder="Comprar"/>
    </form>
</body>
</html>

etianguis/applications/templates/applications/producto_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>Detalles</title>
</head>
<body>
    <h1>{{ producto.nombre}}</h1>
    <h3>Publicado por: {{ producto.id_usuario }}</h3>
    <p>{{ producto.descripcion}}</p>
    <figure>
        {% if producto.imagen %}
        <img src="{{ producto.imagen.url }}">
        {% else %}
        <img src="http://www.404notfound.fr/assets/images/pages/img/androiddev101.jpg">
        {% endif %}
    </figure>
    <h3>Precio: ${{ producto.precio }}</h3>
    <a href="{% url 'applications:product_purchase' producto.id %}">¡Lo quiero!</a>
</body>
</html>

etianguis/applications/templates/applications/producto_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<form action="" method="post" enctype="multipart/form-data">
	{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" />
</form>

</body>
</html>

etianguis/applications/templates/applications/products.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
	<h1>Products</h1>
	<ul>
		{% for product in object_list %}
		<li><a href="{% url 'applications:product_detail' product.id %}">{{ product.nombre }}</a>
		<figure>
			{% if product.imagen %}
			<img src="{{ product.imagen.url }}">
			{% else %}
			<img src="http://www.404notfound.fr/assets/images/pages/img/androiddev101.jpg">
			{% endif %}
		</figure>
		</li>
		{% empty %}
		<li>No articles yet.</li>
		{% endfor %}
	</ul>
	<a href="{% url 'applications:product_create' %}">Add Product</a>
	<a href="{% url 'applications:my_products' %}">My Products</a>
	<a href="{% url 'applications:purchases' %}">My Purchases</a>
	<a href="{% url 'applications:logout' %}">Logout</a>
</body>
</html>

etianguis/applications/templates/applications/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form>
    {{signup_form}}
</form>
</body>
</html>

etianguis/applications/templates/applications/user_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<form action="." method="post">
	{% csrf_token %}
    {{ form.as_p }}
    <input type="submit"></input>
</form>
</body>
</html>

etianguis/applications/templates/applications/user_products.html
<!DOCTYPE html>
<html>
<head>
    <title>Products</title>
</head>
<body>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
    <h1>Your Products</h1>
    <ul>
        {% for product in object_list %}
        {% if product.cantidad == 0 %}
        <li><p>{{ product.nombre }}</p>
        <h3>Vendido</h3>
        {% else %}
        <li><a href="{% url 'applications:product_delete' product.id %}">{{ product.nombre }}</a>
        {% endif %}
        <figure>
            {% if product.imagen %}
            <img src="{{ product.imagen.url }}">
            {% else %}
            <img src="http://www.404notfound.fr/assets/images/pages/img/androiddev101.jpg">
            {% endif %}
        </figure>
        </li>
        {% empty %}
        <li>No articles yet.</li>
        {% endfor %}
    </ul>
    <a href="{% url 'applications:product_create' %}">Add Product</a>
    <a href="{% url 'applications:products' %}">Go back</a>
</body>
</html>

etianguis/applications/templates/applications/user_purchases.html
<!DOCTYPE html>
<html>
<head>
    <title>Purchases</title>
</head>
<body>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
    <h1>Your Purchases</h1>
    <ul>
        {% for purchases in object_list %}
        <li><p>{{ purchases.id_producto }}</p>
        </li>
        {% empty %}
        <li>No articles yet.</li>
        {% endfor %}
    </ul>
    <a href="{% url 'applications:product_create' %}">Add Product</a>
    <a href="{% url 'applications:products' %}">Go Back</a>
</body>
</html>